export enum ConversationError {
  CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_NOT_IN_CONVERSATION = 'USER_NOT_IN_CONVERSATION',
  CONVERSATION_ALREADY_EXISTS = 'CONVERSATION_ALREADY_EXISTS',
}
